"""
cielab_pipeline.py  --  FROZEN CIELAB banana-ripeness pipeline (prototype copy).

AUTO-GENERATED by _generate_pipeline_module.py.  DO NOT EDIT BY HAND.
Every function/constant below is lifted VERBATIM (byte-for-byte) from
    ../CIELAB_Banana_Ripeness_Assignment.ipynb
so the Streamlit prototype runs the exact verified pipeline used for training and
for the frozen 93.5943% official test result.

Regenerate with:  python _generate_pipeline_module.py
Consistency is re-checked by:  python consistency_check.py
"""
from __future__ import annotations

import cv2
import numpy as np
import pandas as pd
from dataclasses import dataclass
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC

RANDOM_SEED = 42

CLASS_ORDER = ["unripe", "ripe", "overripe", "rotten"]

SUBSETS = ["train", "valid", "test"]

IMAGE_SUFFIXES = {".jpg", ".jpeg", ".png", ".bmp"}

EXPECTED_SIZE = (416, 416)

MEDIAN_KERNEL = 3

CLAHE_CLIP_LIMIT = 2.0

CLAHE_TILE_GRID = (8, 8)

MORPH_KERNEL_SIZE = 5

MORPH_OPEN_ITERATIONS = 1

MORPH_CLOSE_ITERATIONS = 1

CONNECTIVITY = 8

HOLE_MAX_COMPONENT_FRACTION = 0.25

HOLE_MAX_IMAGE_FRACTION = 0.05

MIN_FOREGROUND_FRACTION = 0.02

MAX_FOREGROUND_FRACTION = 0.90

LAB_STAT_FEATURES = [
    f"{channel}_{statistic}"
    for channel in ("L", "a", "b")
    for statistic in ("mean", "median", "std", "p10", "p90")
] + ["foreground_fraction"]

CIEDE2000_FEATURES = [f"ciede2000_to_{name}" for name in CLASS_ORDER]

FROZEN_FEATURES = LAB_STAT_FEATURES + CIEDE2000_FEATURES

@dataclass(frozen=True)
class SegmentationResult:
    """Segmentation output together with its automatic diagnostic flag."""

    b_mask: np.ndarray            # raw Otsu mask, before morphology
    final_mask: np.ndarray        # refined mask used for feature extraction
    b_otsu_threshold: float
    foreground_fraction: float
    suspicious_mask: bool

def prepare_cielab_channels(rgb: np.ndarray) -> dict[str, np.ndarray]:
    """Apply median filtering, convert to CIELAB and equalise L* with CLAHE."""
    denoised = cv2.medianBlur(rgb, MEDIAN_KERNEL)

    lab = cv2.cvtColor(denoised, cv2.COLOR_RGB2LAB)
    L8, a8, b8 = cv2.split(lab)

    clahe = cv2.createCLAHE(
        clipLimit=CLAHE_CLIP_LIMIT, tileGridSize=CLAHE_TILE_GRID
    )
    L8_equalised = clahe.apply(L8)

    return {
        "denoised_rgb": denoised,
        "L8_raw": L8,
        "L8": L8_equalised,
        "a8": a8,
        "b8": b8,
    }

def to_true_lab_units(
    L8: np.ndarray, a8: np.ndarray, b8: np.ndarray
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Convert OpenCV 8-bit CIELAB storage into true colorimetric units.

    OpenCV stores L scaled to 0-255 and offsets a and b by +128 to fit an
    unsigned byte. CIEDE2000 is defined over L* in [0, 100] and a*, b* in
    [-128, 127], so this rescaling must be applied before any colorimetric
    calculation. Omitting it would scale every distance incorrectly.
    """
    return (
        L8.astype(np.float64) * (100.0 / 255.0),
        a8.astype(np.float64) - 128.0,
        b8.astype(np.float64) - 128.0,
    )

def fill_small_holes(mask: np.ndarray) -> np.ndarray:
    """Fill enclosed holes only when they are small relative to banana and image."""
    inverted = np.where(mask > 0, 0, 255).astype(np.uint8)
    count, labels, stats, _ = cv2.connectedComponentsWithStats(
        inverted, connectivity=4
    )

    image_area = float(mask.size)
    banana_area = float(np.count_nonzero(mask))
    filled = mask.copy()

    # Background components touching the image border are not enclosed holes.
    border_labels = (
        set(labels[0, :].tolist()) | set(labels[-1, :].tolist())
        | set(labels[:, 0].tolist()) | set(labels[:, -1].tolist())
    )

    for label in range(1, count):
        if label in border_labels:
            continue
        area = float(stats[label, cv2.CC_STAT_AREA])
        if banana_area > 0 and area > HOLE_MAX_COMPONENT_FRACTION * banana_area:
            continue  # large enclosed dark region: genuine rotten peel, keep it
        if area > HOLE_MAX_IMAGE_FRACTION * image_area:
            continue
        filled[labels == label] = 255

    return filled

def segment_banana(b8: np.ndarray) -> SegmentationResult:
    """Segment the banana by automatic Otsu thresholding of b* plus morphology."""
    threshold, mask = cv2.threshold(
        b8, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU
    )
    b_mask = mask.copy()

    kernel = cv2.getStructuringElement(
        cv2.MORPH_ELLIPSE, (MORPH_KERNEL_SIZE, MORPH_KERNEL_SIZE)
    )
    mask = cv2.morphologyEx(
        mask, cv2.MORPH_OPEN, kernel, iterations=MORPH_OPEN_ITERATIONS
    )
    mask = cv2.morphologyEx(
        mask, cv2.MORPH_CLOSE, kernel, iterations=MORPH_CLOSE_ITERATIONS
    )

    count, labels, stats, _ = cv2.connectedComponentsWithStats(
        mask, connectivity=CONNECTIVITY
    )
    if count > 1:
        largest = 1 + int(np.argmax(stats[1:, cv2.CC_STAT_AREA]))
        mask = np.where(labels == largest, 255, 0).astype(np.uint8)

    mask = fill_small_holes(mask)

    fraction = float(np.count_nonzero(mask)) / float(mask.size)
    suspicious = not (
        MIN_FOREGROUND_FRACTION <= fraction <= MAX_FOREGROUND_FRACTION
    )

    return SegmentationResult(
        b_mask=b_mask,
        final_mask=mask,
        b_otsu_threshold=float(threshold),
        foreground_fraction=fraction,
        suspicious_mask=suspicious,
    )

def extract_lab_features(
    L: np.ndarray, a: np.ndarray, b: np.ndarray, mask: np.ndarray
) -> dict[str, float] | None:
    """Return CIELAB statistics computed over segmented banana pixels only."""
    selected = mask > 0
    if not selected.any():
        return None

    row: dict[str, float] = {}
    for name, channel in (("L", L), ("a", a), ("b", b)):
        values = channel[selected]
        row[f"{name}_mean"] = float(values.mean())
        row[f"{name}_median"] = float(np.median(values))
        row[f"{name}_std"] = float(values.std())
        row[f"{name}_p10"] = float(np.percentile(values, 10))
        row[f"{name}_p90"] = float(np.percentile(values, 90))

    row["foreground_fraction"] = float(selected.sum()) / float(mask.size)
    return row

def ciede2000(lab1: np.ndarray, lab2: np.ndarray,
              k_L: float = 1.0, k_C: float = 1.0, k_H: float = 1.0) -> np.ndarray:
    """CIEDE2000 colour difference between two CIELAB colours (true units)."""
    lab1 = np.asarray(lab1, dtype=np.float64)
    lab2 = np.asarray(lab2, dtype=np.float64)
    L1, a1, b1 = lab1[..., 0], lab1[..., 1], lab1[..., 2]
    L2, a2, b2 = lab2[..., 0], lab2[..., 1], lab2[..., 2]

    # Step 1: chroma and the G factor that compensates low-chroma blue behaviour
    C1, C2 = np.hypot(a1, b1), np.hypot(a2, b2)
    C_bar7 = (0.5 * (C1 + C2)) ** 7
    G = 0.5 * (1.0 - np.sqrt(C_bar7 / (C_bar7 + 25.0 ** 7)))

    a1p, a2p = (1.0 + G) * a1, (1.0 + G) * a2
    C1p, C2p = np.hypot(a1p, b1), np.hypot(a2p, b2)

    h1p = np.where((np.abs(a1p) + np.abs(b1)) == 0.0, 0.0,
                   np.degrees(np.arctan2(b1, a1p)) % 360.0)
    h2p = np.where((np.abs(a2p) + np.abs(b2)) == 0.0, 0.0,
                   np.degrees(np.arctan2(b2, a2p)) % 360.0)

    # Step 2: lightness, chroma and hue differences
    dLp = L2 - L1
    dCp = C2p - C1p

    dhp = h2p - h1p
    dhp = np.where(dhp > 180.0, dhp - 360.0, dhp)
    dhp = np.where(dhp < -180.0, dhp + 360.0, dhp)
    dhp = np.where(C1p * C2p == 0.0, 0.0, dhp)
    dHp = 2.0 * np.sqrt(C1p * C2p) * np.sin(np.radians(0.5 * dhp))

    # Step 3: weighting functions and the rotation term
    Lp_bar = 0.5 * (L1 + L2)
    Cp_bar = 0.5 * (C1p + C2p)

    h_sum, h_diff = h1p + h2p, np.abs(h1p - h2p)
    hp_bar = np.where(
        h_diff <= 180.0, 0.5 * h_sum,
        np.where(h_sum < 360.0, 0.5 * (h_sum + 360.0), 0.5 * (h_sum - 360.0)),
    )
    hp_bar = np.where(C1p * C2p == 0.0, h_sum, hp_bar)

    T = (1.0
         - 0.17 * np.cos(np.radians(hp_bar - 30.0))
         + 0.24 * np.cos(np.radians(2.0 * hp_bar))
         + 0.32 * np.cos(np.radians(3.0 * hp_bar + 6.0))
         - 0.20 * np.cos(np.radians(4.0 * hp_bar - 63.0)))

    Cp_bar7 = Cp_bar ** 7
    R_C = 2.0 * np.sqrt(Cp_bar7 / (Cp_bar7 + 25.0 ** 7))
    d_theta = 30.0 * np.exp(-(((hp_bar - 275.0) / 25.0) ** 2))
    R_T = -R_C * np.sin(np.radians(2.0 * d_theta))

    Lp_bar_sq = (Lp_bar - 50.0) ** 2
    S_L = 1.0 + (0.015 * Lp_bar_sq) / np.sqrt(20.0 + Lp_bar_sq)
    S_C = 1.0 + 0.045 * Cp_bar
    S_H = 1.0 + 0.015 * Cp_bar * T

    term_L = dLp / (k_L * S_L)
    term_C = dCp / (k_C * S_C)
    term_H = dHp / (k_H * S_H)

    return np.sqrt(term_L ** 2 + term_C ** 2 + term_H ** 2
                   + R_T * term_C * term_H)

def build_prototypes(training_features: pd.DataFrame) -> pd.DataFrame:
    """Construct the four training-only CIELAB class prototypes."""
    if not training_features["subset"].eq("train").all():
        raise RuntimeError(
            "Validation or test data entered prototype construction."
        )

    rows = []
    for class_name in CLASS_ORDER:
        class_rows = training_features[
            training_features["ground_truth_class"] == class_name
        ]
        if class_rows.empty:
            raise RuntimeError(f"No training rows for class: {class_name}")
        rows.append({
            "class_name": class_name,
            "prototype_L": float(class_rows["L_median"].median()),
            "prototype_a": float(class_rows["a_median"].median()),
            "prototype_b": float(class_rows["b_median"].median()),
            "training_images": int(len(class_rows)),
            "prototype_source_subset": "train",
        })

    return pd.DataFrame(rows)

def add_ciede2000_features(
    features: pd.DataFrame, prototypes: pd.DataFrame
) -> pd.DataFrame:
    """Append one CIEDE2000 distance per class prototype."""
    enhanced = features.copy()
    image_colour = enhanced[["L_median", "a_median", "b_median"]].to_numpy(
        dtype=np.float64
    )

    for _, prototype in prototypes.iterrows():
        reference = np.array(
            [prototype["prototype_L"],
             prototype["prototype_a"],
             prototype["prototype_b"]],
            dtype=np.float64,
        )
        enhanced[f"ciede2000_to_{prototype['class_name']}"] = ciede2000(
            image_colour, np.broadcast_to(reference, image_colour.shape)
        )

    values = enhanced[CIEDE2000_FEATURES].to_numpy(dtype=np.float64)
    if not np.isfinite(values).all():
        raise RuntimeError("Non-finite CIEDE2000 features were produced.")
    return enhanced

def make_model() -> Pipeline:
    """Return the agreed untuned baseline classifier."""
    return Pipeline([
        ("scaler", StandardScaler()),
        ("svm", SVC()),
    ])

# --------------------------------------------------------------------------- #
# Thin composition helpers for single-image inference.
# These ONLY chain the verbatim functions above in the SAME order as notebook
# cell 10 (extract_image_features). No pipeline parameter/logic is changed.
# --------------------------------------------------------------------------- #
EXPECTED_SIZE_HW = (EXPECTED_SIZE[1], EXPECTED_SIZE[0])  # (w, h) for cv2.resize


def prepare_rgb_from_bytes(data: bytes) -> np.ndarray:
    """Decode uploaded bytes to a 416x416 uint8 RGB array.

    Mirrors the notebook's load_native_rgb() decode/resize contract exactly
    (cv2.imdecode COLOR -> BGR2RGB -> INTER_AREA resize when size differs).
    """
    encoded = np.frombuffer(data, dtype=np.uint8)
    if encoded.size == 0:
        raise ValueError("Empty image file.")
    bgr = cv2.imdecode(encoded, cv2.IMREAD_COLOR)
    if bgr is None:
        raise ValueError("Image could not be decoded.")
    rgb = cv2.cvtColor(bgr, cv2.COLOR_BGR2RGB)
    if rgb.shape[:2] != EXPECTED_SIZE:
        rgb = cv2.resize(rgb, EXPECTED_SIZE_HW, interpolation=cv2.INTER_AREA)
    if rgb.shape != (*EXPECTED_SIZE, 3) or rgb.dtype != np.uint8:
        raise ValueError(f"Unexpected prepared array: {rgb.shape}, {rgb.dtype}")
    return rgb


def image_feature_row(rgb: np.ndarray, prototypes: "pd.DataFrame"):
    """Run the frozen pipeline on one RGB image -> (feature_df_20, channels, segmentation).

    Same sequence as notebook cell 10: prepare_cielab_channels -> segment_banana
    -> to_true_lab_units -> extract_lab_features -> add_ciede2000_features.
    Returns feature_df=None if segmentation yields an empty mask (as the notebook does).
    """
    channels = prepare_cielab_channels(rgb)
    segmentation = segment_banana(channels["b8"])
    L, a, b = to_true_lab_units(channels["L8"], channels["a8"], channels["b8"])
    stats = extract_lab_features(L, a, b, segmentation.final_mask)
    if stats is None:
        return None, channels, segmentation
    row = pd.DataFrame([stats])
    enhanced = add_ciede2000_features(row, prototypes)
    feature_df = enhanced[FROZEN_FEATURES].astype(np.float64)
    return feature_df, channels, segmentation
